'''
nmappy python nmap tool
'''

import nmap

print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo;,;l0WMMMNd;:OMMNd;,,;lKMMMMMMM0l,,,:OWMMMMMNx;,,,:kWMMMMMXo;,,,,;:lxXWMWO:,,,,,;coONM0c,;xNMMMWO:,:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXO0WMMMMMMMMMWXk0WM0'    ,0MMMX; .dWMK,     ;KMMMMMK;     lWMMMMWk.     '0MMMMM0'  .;:;.  'xWWo   '::'   :KNo. .oNMWO'  :KW0kXWMMMMMMMMMWOOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMWXko;..cXMMMMMWXkl;..lNM0' .'. ,0MMX; .dWM0,  ,,  lNMMMNc  ;,  lWMMMMK; .l,   :XMMMM0'  cNMWk.  ,KWo  .kMMNl   oWNo. .dN0'  cXMNl..;lkXWMMMMMXc..;okXWMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMWXkl;...;lkXWMWKkl;...;okXMM0' .xl  ;KMX; .dWM0,  lk. .xWMWd. ;O;  lWMMMNc  cNk:. .oWMMM0'  cNMWk.  ;KWd  .kMMNl  .dWMNd. .l,  cXMMMXOo:...;lkKWMMXko;...;okXWMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMNd.  ,lkKWMMMMNo. .,okXWMMMMM0' .kXl  ;KX; .dWMK,  lNo  '0Wk. .OK;  lWMMWx. ,0MNXo  .OWMM0'  .cc:.  ,OWWd   ,cc,. .lXMMMNd.    cXMMMMMMMWXOd;. .oNMMMMWXko;. .dNMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMNd'  ,lkKWMMMMNo. .,lkXWMMMMM0' .xMXl. :O: .dWMK,  lWK;  cO; .oNK;  lWMM0'  'llll;.  ;KMM0'  .'',;lxXMMWd   .'',:oOWMMMMMNo.  cXMMMMMMMMWKkl,. .oNMMMMWKxl,. 'dNMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMWXOd:...;lkXWMWXOo:...;okXMM0' .xMMNo. ;' .dWM0,  lWMO'  .  :XMK;  lWMX:  ......'.   lNM0'  :XNWWMMMMMWd  .xWWWMMMMMMMMMMk.  dWMMMMMXkl;...;okXWMWXxl,...:oOXWMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMWXOd:..cXMMMMMWXOo:..lNM0' .xMMMNo.   .dWM0,  lWMWd.   '0MMK;  lWWd. .kNNNNNNXl  .xW0'  cNMMMMMMMMWd  .kMMMMMMMMMMMMMk.  dMMMMMNl..;oOXWMMMMMX:.':oOXWMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNO0WMMMMMMMMMWXOKWMK:.,OMMMMNd'..,OWMXc..dWMMXl..'kWMWXl..dWK:..dWMMMMMMMK:..cXK:..oWMMMMMMMMWx'.,OMMMMMMMMMMMMM0;.'xMMMMMW0OXWMMMMMMMMMW0OXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKXWMMMMMWNKKXWMMWNKKNMMMMNXKXWMMMMNKXNMWXKXWMMMMMMMMMNKKXWWXKKNMMMMMMMMMMWXKXWMMMMMMMMMMMMMWXKXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")


def helport():
	what_ports = input(f'PORT / PORT RANGE:\n\t>>')
	if what_ports == "help":
		print("Enter the port / ports you would like to scan: (ex. 23, 23-200)")
		helport()
	return what_ports

def helpip():
	what_ip = input(f'IP:\n\t>>')
	if what_ip == "help":
		print("Enter the ip address for which you would like to scan: (ex. 8.8.8.8)")
		helpip()
	return what_ip

def helpopt():
	what_options = input(f'NMAP OPTIONS:\n\t>>')
	if what_options == "help":
		print("Enter the additional opetions you would like to apply to your scan: (ex. -sL)")
		helpopt()
	return what_options


def initer():
	commander = input("\n>>")
	if commander == "nmappy out":
		return
	elif commander == "nmappy init":
		print("\nEnter the information you would like to scan with. For help type \"help\"\n")

		target = str(helpip())
		t_ports = helport()

		scanner = nmap.PortScanner()

		res = scanner.scan(target, t_ports)

		# print(f'\nTARGET IS: {scanner[target].state()}')
		# print(f'\n{scanner.command_line()}')

		for host in scanner.all_hosts():
		     print('\n\nHost : %s (%s)' % (host, scanner[host].hostname()))
		     print('State : %s' % scanner[host].state())
		     for proto in scanner[host].all_protocols():
		         print('----------')
		         print('Protocol : %s' % proto)
		 
		         lport = scanner[host][proto].keys()
		         for port in lport:
		             print ('port : %s\tstate : %s' % (port, scanner[host][proto][port]['state']))
		initer()
	

initer()

#initiate scan


#print output

print("\n\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo;,;l0WMMMNd;:OMMNd;,,;lKMMMMMMM0l,,,:OWMMMMMNx;,,,:kWMMMMMXo;,,,,;:lxXWMWO:,,,,,;coONM0c,;xNMMMWO:,:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXO0WMMMMMMMMMWXk0WM0'    ,0MMMX; .dWMK,     ;KMMMMMK;     lWMMMMWk.     '0MMMMM0'  .;:;.  'xWWo   '::'   :KNo. .oNMWO'  :KW0kXWMMMMMMMMMWOOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMWXko;..cXMMMMMWXkl;..lNM0' .'. ,0MMX; .dWM0,  ,,  lNMMMNc  ;,  lWMMMMK; .l,   :XMMMM0'  cNMWk.  ,KWo  .kMMNl   oWNo. .dN0'  cXMNl..;lkXWMMMMMXc..;okXWMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMWXkl;...;lkXWMWKkl;...;okXMM0' .xl  ;KMX; .dWM0,  lk. .xWMWd. ;O;  lWMMMNc  cNk:. .oWMMM0'  cNMWk.  ;KWd  .kMMNl  .dWMNd. .l,  cXMMMXOo:...;lkKWMMXko;...;okXWMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMNd.  ,lkKWMMMMNo. .,okXWMMMMM0' .kXl  ;KX; .dWMK,  lNo  '0Wk. .OK;  lWMMWx. ,0MNXo  .OWMM0'  .cc:.  ,OWWd   ,cc,. .lXMMMNd.    cXMMMMMMMWXOd;. .oNMMMMWXko;. .dNMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMNd'  ,lkKWMMMMNo. .,lkXWMMMMM0' .xMXl. :O: .dWMK,  lWK;  cO; .oNK;  lWMM0'  'llll;.  ;KMM0'  .'',;lxXMMWd   .'',:oOWMMMMMNo.  cXMMMMMMMMWKkl,. .oNMMMMWKxl,. 'dNMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMWXOd:...;lkXWMWXOo:...;okXMM0' .xMMNo. ;' .dWM0,  lWMO'  .  :XMK;  lWMX:  ......'.   lNM0'  :XNWWMMMMMWd  .xWWWMMMMMMMMMMk.  dWMMMMMXkl;...;okXWMWXxl,...:oOXWMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMWXOd:..cXMMMMMWXOo:..lNM0' .xMMMNo.   .dWM0,  lWMWd.   '0MMK;  lWWd. .kNNNNNNXl  .xW0'  cNMMMMMMMMWd  .kMMMMMMMMMMMMMk.  dMMMMMNl..;oOXWMMMMMX:.':oOXWMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNO0WMMMMMMMMMWXOKWMK:.,OMMMMNd'..,OWMXc..dWMMXl..'kWMWXl..dWK:..dWMMMMMMMK:..cXK:..oWMMMMMMMMWx'.,OMMMMMMMMMMMMM0;.'xMMMMMW0OXWMMMMMMMMMW0OXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKXWMMMMMWNKKXWMMWNKKNMMMMNXKXWMMMMNKXNMWXKXWMMMMMMMMMNKKXWWXKKNMMMMMMMMMMWXKXWMMMMMMMMMMMMMWXKXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
